apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image:  marcossousalima/kube-news:v1
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: config-map-app 
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-app
data:
    DB_DATABASE: "kubenews"
    DB_USERNAME: "kubenews"
    DB_PASSWORD: "Pg#123"
    DB_HOST: postgresql

  
          
