version: '3'

networks:
  network-kubenews:
    driver: bridge

volumes:
  kubedevnews:
  pgadmin-data:

services:

  postgresql:
    image: postgres:14.5
    container_name: postgresql
    networks:
      - network-kubenews
    restart: always
    volumes:
      - kubedevnews:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: kubedevnews

  apinode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apinode
    networks:
      - network-kubenews
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgresql
    networks:
      - network-kubenews
    ports:
      - 16543:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password

