name: CI-CD

on: 
  push:
    branches: ["main"]
    
jobs:
  CI:  
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo código
        uses: actions/checkout@v4.1.5
      - name: autenticação no docker hub 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.TOKEN}}

      - name: build da imagem
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            marcossousalima/kube-news-pipeline:v${{github.run_number}}

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Install kubectl and gke-gcloud-auth-plugin
        run: |
          gcloud components install kubectl
          gcloud components install gke-gcloud-auth-plugin
          echo 'export USE_GKE_GCLOUD_AUTH_PLUGIN=True' >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials kube-news --zone us-central1-c --project estudo-devops-428820

      - name: Update deployment image
        run: |
          sed -i 's|image: marcossousalima/kube-news-pipeline:latest|image: marcossousalima/kube-news-pipeline:v${{github.run_number}}|g' ./k8s/deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./k8s/deployment.yaml

      - name: Force restart pods
        run: |
          kubectl rollout restart deployment web

      - name: List All pods
        run: |
          kubectl get pods --all-namespaces

