name: CI-CD

on: 
  push:
    branches: ["main"]
    
jobs:
  CI:  
   runs-on: ubuntu-latest
   steps:
      - name: Obtendo código
        uses: actions/checkout@v4.1.5
      - name: autenticação no docker hub 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: build da imagem
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            marcossousalima/kube-news-pipeline/v1
            marcossousalima/kube-news-pipeline/latest
