name: CI-CD

on: 
  push:
    branches: ["main"]
    
jobs:
  CI:  
   runs-on: ubuntu-latest
   steps:
      - name: Obtendo código
        uses: actions/checkout@v4.1.5
      - name: autenticação no docker hub 
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: build da imagem
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            marcossousalima/kube-news-pipeline:v${{ github.run_number}}
            marcossousalima/kube-news-pipeline:latest

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps: 
      - uses: actions/checkout@v3.1.0
      
      - name: Definindo o context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S }} 
      - name: Execucao do manifesto
        uses: Azure/k8s-deploy@v4
        with:
          images: marcossousalima/kube-news-pipeline:v${{ github.run_number}}
          manifests: |
            k8s/deployment.yaml
